quick-test:
	cargo test -- --nocapture

verbose-test:
	cargo test --features verbose-tests -- --nocapture

HEADER_PATH = ""
HEADER_DIR = ""
get-headers:
	#mkdir -p $(HEADER_DIR)
	#wget -q $(HEADER_PATH)/pkcs11.h -O $(HEADER_DIR)/pkcs11.h
	#wget -q $(HEADER_PATH)/pkcs11f.h -O $(HEADER_DIR)/pkcs11f.h
	#wget -q $(HEADER_PATH)/pkcs11t.h -O $(HEADER_DIR)/pkcs11t.h
